### ISSUE TITLE
if mower is lifted, Ardumower should go into ERROR

### ISSUE THREAD

**Issue by autega** [Ardumower/ardumower#10]
maybe we can use IMU for this

**Comment by maxbki** [comment]
This feature is already implemented and tested. Please tell us if it is broken or not.
Please check https://github.com/Ardumower/ardumower/blob/master/ardumower/robot.cpp#L2012

**Comment by greymfm** [comment]
I think he means that the mower is lifted in straight (level) without a tilt. That will be difficult to detect as during normal mowing the mower z acceleration (lifting) can have the same magnitude for the same time...

**Comment by netlars** [comment]
tilt is working
