### ISSUE TITLE
External tilt pin

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#100]
würdest du mir die tilt Funktion in die Azurit einpflegen so dass man das über die pfod ein und ausschalten kann als state würde ich Tilt_Stop benötigen der einfach alle Motoren ausschaltet und sobald der Eingang wieder weg ist den Mower wieder startet im vorherigen State. das wäre nett ich brauche stunden mich in den code in der gänze einzulesen. bei dem tilt eingang muss der pullup aktiviert sein. Danke im voraus

**Comment by netlars** [comment]
Tilt ist vorhanden in der Pfod App
