### ISSUE TITLE
missing manual

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#109]
Software-Anleitung (Schritt 1, 2, 3...)

**Comment by vkuehn** [comment]
hast Du auf http://wiki.ardumower.de/index.php?title=Hauptseite geschaut, dort gibt es diverse Anleitungen...!?

**Comment by greymfm** [comment]
Geht um eine bebilderte Anleitung für Jedermann - die Anleitung im Wiki ist für die meisten noch nicht einfach genug - der Benutzer muss noch mehr geführt werden und vieles unwichtige muss dabei verschwinden und wichtiges muss mehr hervorgehoben werden...

**Comment by vkuehn** [comment]
hmm grundsätzlich hast Du recht. bin aber nicht sicher ob es da EINE Anleitung geben kann wenn man sich die viel Zahl der verschiedenen fertigen Lösungen anschaut...

**Comment by netlars** [comment]
Wiki und Forum sind gut!
