### ISSUE TITLE
PCB 1.3: ultrasonic sliders

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#118]
er funktioniert sieht aber so aus wie wenn die werte (Value in cm sind damit ist natürlich trigger below und slow below im standard sehr hoch und die regler Skalierung ist dafür falsch beide regler sind für eine richtige Einstellung fas am ende der möglichkeiten
dafür scheinen die werte aber sehr sauber zu sein in cm kommt es recht gut hin
am besten man ändert die Skalierung der trigger und slow regler

**Comment by netlars** [comment]
Regler stehen mittig und funktionieren bei mir gut.
Reopen falls jemand anderer Meinung ist.
