### ISSUE TITLE
Wrong battery voltage conversion factor

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#16]
Shown battery voltage is incorrect (about 0.3v lower than actual 28.2v). 

For me it looks like the factor is wrong:
------- currently, it is --------
batFactor       = 0.495;  
double batvolt = (double)batADC \* batFactor / 10;

------- it should be --------
Here's the calculation for the mathematical correct factor (we should use the C macro below in the code!):

Add this to 'drivers.h':

// macro computes ADC-to-voltage factor for given voltage divider
// ADC 5v/1024 => volt per ADC value
# define ADC2VOLT_FACTOR(VOLT_DIVIDER_TOP, VOLT_DIVIDER_BOTTOM)  ( (VOLT_DIVIDER_TOP+VOLT_DIVIDER_BOTTOM)/VOLT_DIVIDER_BOTTOM \* (5.0/1024) )

Use the macro in mower.cpp:

batFactor = ADC2VOLT_FACTOR(47.0, 5.1) \* 10.0;

result will be:  batFactor = 0.4988

**Comment by autega** [comment]
hmm, not sure if we should automate this

**Comment by autega** [comment]
Now I'm sure. :-)

**Comment by netlars** [comment]
done
