### ISSUE TITLE
optimize default mower motor max power / wait time for blocked blade

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#20]
A motor driver SF/error disables driver (enable pin):

Start current:
http://wiki.ardumower.de/images/c/cd/Mower2_start_current.png

Blocked mower blade (500 ms detection time, 5s wait time):
http://wiki.ardumower.de/images/1/18/Mower4_blocked_500ms_detect_5s_wait.png

In the Ardumower current code (detection time and very short wait time), the max. allowed power is 45 Watt (parallel dual driver) for no driver error to appear.

=> This power level could be set higher if the wait time is extended to 5 seconds.

**Comment by autega** [comment]
done with: 2ad982edc52ef3d0121d58041205e5d281d60fe6
