### ISSUE TITLE
Implement Wifi code (pfodapp compatible remote-app)

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#27]
Implement a website (Javascript code) that implements the pfodApp remote-app protocol:

http://www.ardumower.de/index.php/de/forum/dies-und-das/518-javascript-programmierer-gesucht

**Comment by FredericG-BE** [comment]
So my understanding is that in this approach, the JavaScript code would send HTTP request holding fpod commands

**Comment by greymfm** [comment]
Hmm... we should close this issue? As you already found out a better approach!
