### ISSUE TITLE
reduce interrupts from odometry

### ISSUE THREAD

**Issue by autega** [Ardumower/ardumower#35]
using only one encoder channel as default
so set 
twoWayOdometrySensorUse = 0

in mower.cpp as default

**Comment by greymfm** [comment]
Number of total interrupts can further be reduced by choosing (old) 9.6 kHz ADC sample rate in adc.cpp again:

  //sampleRate = SRATE_38462;
  sampleRate = SRATE_9615;

We should use 9.6 Khz until we have futher optimized the code/changed to Due.

**Comment by autega** [comment]
are there any disadvantages in regard of perimeter tracking etc?

**Comment by autega** [comment]
done with 1af7590e5eddb8b6e9c4a9788ce52a152935dba6
