### ISSUE TITLE
Clear error message for end-user

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#51]
Improve displayed error message for end-user:

--Error counters--

Settings missing
ADC calibration missing
RTC hardware
RTC datetime invalid
Gear motor left 
Gear motor right
Odometry left
Odometry right 
Mower motor 
Mower motor current
Perimeter timeout
Perimeter tracking 
Battery
Charger
GPS hardware
GPS sky data
IMU hardware
IMU calibration missing
IMU tilt

**Comment by netlars** [comment]
done
