### ISSUE TITLE
Precise motor control in charging station

### ISSUE THREAD

**Issue by greymfm** [Ardumower/ardumower#56]
Motor need to be controlled precisely in charging station:
1. Stop immediately: Robot enters charging station and need to stop immediately. Currently, after connecting, it drives a little reverse sometimes and accidently disconnects.
2. Precise reverse: Robot leaves charging station and need to drive exactly reverse - currently, it drives reversely in a roll sometimes and accidently crosses perimeter.

**Comment by netlars** [comment]
i think, this bug is gone
