### ISSUE TITLE
please show softwareversion in setup menu 

### ISSUE THREAD

**Issue by pemiso** [Ardumower/ardumower#62]
Please always fill-in below/Bitte unbedingt ausfüllen!

--English--
Your battery voltage (12v, 24v): 24v
Your gear motor (Ardumower, other): DENNA
Your Ardumower software version (pfodApp->Info): Azurit 1.0a4
Your Arduino (Mega or Due): Mega 2560
Your PCB version (printed on PCB): 0.5
Your PCB mounted parts configuration (default or custom and how): default
Odometry sensor (yes/no)? yes
Ardumower chassis (yes/no)? no (DENNA)
Exact error description: no error! Could it be possible to show installed software version within the setup menus (Mega - command 'd', Nano - command '1')?

--Deutsch--
Deine Akku-Spannung (12v, 24v): 24v
Dein Antriebsmotor (Ardumower, anderer): DENNA
Deine Ardumower-Software Version: (pfodApp->Info): Azurit 1.0a4
Deine PCB-Version (siehe Aufdruck): 0.5
Dein Arduino (Mega oder Due): Mega 2560
Deine PCB Bauteilbestückung (Standard oder abweichend und wie): Standard
Odometrie sensor (ja/nein)? ja
Ardumower Chassis (ja/nein)? nein (DENNA)
Genaue Fehlerbeschreibung: Kein Fehler, sondern ein Wunsch: könnte man die installierte Softwareversion innerhlab der Setup-Menus (Kommando 'd' beim Mega, '1' beim Nano) anzeigen lassen?

**Comment by netlars** [comment]
added to console menu d https://github.com/Ardumower/ardumower/commit/5ea1b19f6c9a32648ab67cbf668d9f9a8de17d7c
