### ISSUE TITLE
automatisches Abschalten / Unterspannungsabschaltung

### ISSUE THREAD

**Issue by Kurzschuss** [Ardumower/ardumower#68]
Mann sollte evl ändern  wenn das möglich ist, das wenn eine Verbindung mit dem BT Modul oder Wlan Modul oder der seriellen Konsolle besteht keine Abschaltung wegen Inaktivität vorgennommen wird. 
Außerdem wäre es Hilfreich wenn man weiß warum abgeschaltet wird.
Deswegen evl eine Ausgabe vielleicht in der Form:
1. Abschaltung wegen Inaktivität
2. Abschaltung wegen Unterspannung

**Comment by netlars** [comment]
erledigt
