### ISSUE TITLE
perimeter.isInside() is slow in reporting transitions.

### ISSUE THREAD

**Issue by FredericG-BE** [Ardumower/ardumower#71]
perimeter.isInside() takes its decision on a filtered version of the magnitude and so it takes some time before isInside() reports a transition. As a result the variables perimeterInside and perimeterLastTransitionTime take some time to change while the variable perimeterMag changes immediately.

Some code rely on a mixture of  perimeterMag  and perimeterLastTransitionTime and this can have strange effects for a short time. 

After a discussion we decided: 
- the code should not use the magnitude directly, only pfod or conslue for debug-purposes, but no decisions should be bases on magnitude
- make isInside() a bit more intelligent. When mag is high, it decides on mag. Else it uses the filtered value

**Comment by netlars** [comment]
obsolete
