### ISSUE TITLE
Betriebsstundenzähler

### ISSUE THREAD

**Issue by Kurzschuss** [Ardumower/ardumower#86]
Betriebsstundenzähler für den Mäher Komplett und für den Mähmotor zum Messerwechseln

**Comment by netlars** [comment]
Betriebsstundenzähler Mäher Komplett schon vorhanden.

Betriebsstundenzähler Mähmesser ergänzt in f2b2a2fe4c9bdb5c33dbd8d7c03db1e6637607a8
